//! The Curator, mechanical half: collect `WorkReported` notes from cards that
//! reached Done and park them as dated files under the project's memory, then
//! regenerate the index from those files. Pure functions plus the file writes;
//! the judging layer (contradictions, obsolescence, reorganisation) is a later,
//! model-driven pass that edits these same files.

use std::path::Path;

use harness_domain::{Card, Event, Status};
use harness_ports::StoredEvent;

/// One promoted note, ready to become a file.
#[derive(Debug, Clone, PartialEq)]
pub struct Promotion {
    pub card_id: String,
    pub file_name: String,
    pub markdown: String,
}

/// Notes reported by cards that are Done and not yet curated. Anything else —
/// running, rejected, forgotten — stays out: promoting work that was thrown
/// away puts false facts into memory.
pub fn plan_promotions(
    history: &[StoredEvent],
    since_seq: u64,
    cards: &[Card],
) -> Vec<Promotion> {
    let done: std::collections::HashSet<&str> = cards
        .iter()
        .filter(|c| c.status == Status::Done)
        .map(|c| c.id.as_str())
        .collect();
    let mut out = Vec::new();
    for stored in history {
        if stored.seq <= since_seq {
            continue;
        }
        let Event::WorkReported { card_id, summary, notes } = &stored.event else {
            continue;
        };
        if !done.contains(card_id.as_str()) {
            continue;
        }
        let mut body = String::new();
        if !summary.trim().is_empty() {
            body.push_str(summary.trim());
            body.push_str("\n\n");
        }
        for note in notes.iter().filter(|n| !n.trim().is_empty()) {
            body.push_str(&format!("- {note}\n"));
        }
        out.push(Promotion {
            card_id: card_id.to_string(),
            file_name: format!("{}-{}.md", stored.seq, slug(card_id.as_str())),
            markdown: format!(
                "---\ncard: {}\nseq: {}\n---\n\n{}",
                card_id, stored.seq, body
            ),
        });
    }
    out
}

fn slug(s: &str) -> String {
    let cleaned: String = s
        .to_lowercase()
        .chars()
        .take(32)
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    cleaned.trim_matches('-').to_string()
}

/** The index is generated by code from the files' own headers — never written
 *  by a model, so a parent summary cannot go stale when a child changes. */
pub fn render_index(area_files: &[(String, Vec<String>)]) -> String {
    let mut out = String::from("# Areas\n\n");
    for (name, headers) in area_files {
        out.push_str(&format!("## {name}\n"));
        for h in headers {
            out.push_str(&format!("- {h}\n"));
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use harness_domain::{Actor, CardId, Review};

    fn card(id: &str, status: Status) -> Card {
        Card {
            id: CardId::new(id),
            title: id.into(),
            status,
            current_run: None,
            agent_id: "builder".into(),
            cost_usd: 0.0,
            turns: 0,
            runs: 1,
            last_review: Some(Review { by: Actor::Human, approved: true, reason: String::new() }),
            session_id: None,
            worktree: None,
            branch: None,
            depends_on: Vec::new(),
            budget_paused: false,
        }
    }

    fn reported(seq: u64, card: &str, summary: &str, notes: &[&str]) -> StoredEvent {
        StoredEvent {
            seq,
            ts_ms: 0,
            event: Event::WorkReported {
                card_id: CardId::new(card),
                summary: summary.into(),
                notes: notes.iter().map(|n| n.to_string()).collect(),
            },
        }
    }

    #[test]
    fn only_done_cards_are_promoted_and_only_after_the_watermark() {
        let history = vec![
            reported(5, "old", "before the watermark", &[]),
            reported(10, "done", "kept", &["fact"]),
            reported(11, "rejected", "thrown-away work", &[]),
        ];
        let cards = vec![
            card("done", Status::Done),
            card("rejected", Status::Ready),
        ];
        let promotions = plan_promotions(&history, 7, &cards);
        assert_eq!(promotions.len(), 1, "watermark skips old, Done-only promotes");
        assert_eq!(promotions[0].card_id, "done");
        assert!(promotions[0].markdown.contains("- fact"));
    }

    #[test]
    fn the_index_lists_what_exists_no_more() {
        let idx = render_index(&[
            ("auth".into(), vec!["tokens live here".into()]),
            ("seo".into(), vec![]),
        ]);
        assert!(idx.contains("## auth") && idx.contains("- tokens live here"));
        assert!(idx.contains("## seo"));
        // An empty area still shows up: knowing it is empty is information.
    }
}
