//! The words the Rust side and the sidecar say to each other, and the one
//! place they live.
//!
//! Everything between `crates/adapters/agent-sidecar` and `sidecar/index.mjs`
//! travels as JSON, and JSON is where both compilers stop looking. A tool
//! name, an event kind, a flag on the run spec: each is a string typed once in
//! Rust and once in JavaScript, with nothing anywhere obliging the two to
//! agree. When they disagree the failure is silent — not a crash, not a type
//! error, just a branch that never runs.
//!
//! That is not hypothetical and it was not cheap. The guard for
//! `subagents: false` compared against `Task`; the model calls the tool
//! `Agent`. The comparison was wrong the day it was written and stayed wrong
//! for every version after it, so a conversation that forbade fan-out opened
//! nine subagents — four of them opened *by* subagents, because the depth
//! counter sat behind the same dead comparison. Nothing failed. Nothing could:
//! the two halves were never introduced.
//!
//! So this module owns them and writes the JavaScript, the same way
//! [`crate::vocabulary`] owns the operator's words and writes the TypeScript.
//! The same rule holds and it is the one that matters: **the strings are not
//! typed here either.** An event kind comes from serialising a real
//! [`RunEvent`], so a kind in the sidecar is by construction the kind the
//! adapter parses. Rename a variant and both halves change, or neither does.

use harness_ports::{RunEvent, SUBAGENT_TOOLS};

/// One of every `RunEvent`, so the kinds can be read off the wire format
/// rather than guessed at.
///
/// Written by hand, so `every_variant_is_listed` below reads the enum's own
/// source and refuses anything left out. A kind the sidecar may emit and this
/// list has never heard of is a kind the adapter will not parse.
fn one_of_each() -> Vec<RunEvent> {
    vec![
        RunEvent::Started { session_id: String::new() },
        RunEvent::Text { text: String::new(), parent_tool_use_id: None },
        RunEvent::Delta { text: String::new(), parent_tool_use_id: None },
        RunEvent::Thinking { text: String::new(), parent_tool_use_id: None },
        RunEvent::Thought { text: String::new() },
        RunEvent::Notice { text: String::new() },
        RunEvent::LocalOutput { text: String::new() },
        RunEvent::Failed { message: String::new() },
        RunEvent::Turns { count: 0 },
        RunEvent::Commands { commands: Vec::new() },
        RunEvent::BackgroundTasks { tasks: Vec::new() },
        RunEvent::UserMessage { text: String::new() },
        RunEvent::UserQueued { queue_id: String::new(), text: String::new() },
        RunEvent::UserRead { queue_id: String::new() },
        RunEvent::ApprovalRequested {
            request_id: String::new(),
            tool: String::new(),
            summary: String::new(),
        },
        RunEvent::ApprovalAnswered {
            request_id: String::new(),
            unanswered: false,
            allow: false,
        },
        RunEvent::ToolUse {
            tool: String::new(),
            summary: String::new(),
            tool_use_id: None,
            parent_tool_use_id: None,
            added: None,
            removed: None,
        },
        RunEvent::ToolResult {
            tool_use_id: String::new(),
            ok: false,
            summary: String::new(),
            detail: None,
        },
        RunEvent::Usage {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: 0,
            cache_creation_tokens: 0,
            model: None,
            subagent: false,
        },
        RunEvent::Done {
            session_id: None,
            cost_usd: None,
            turns: None,
            result: None,
            error: None,
        },
    ]
}

/// The `kind` of one event, as serde actually writes it.
fn kind_of(event: &RunEvent) -> String {
    serde_json::to_value(event)
        .ok()
        .and_then(|v| v["kind"].as_str().map(str::to_string))
        .unwrap_or_default()
}

/// Every event kind that can cross the pipe, in the wire's own spelling.
pub fn event_kinds() -> Vec<String> {
    let mut kinds: Vec<String> = one_of_each().iter().map(kind_of).collect();
    kinds.sort();
    kinds.dedup();
    kinds
}

/// The module the sidecar imports. Generated by `pnpm codegen`; never edited.
pub fn javascript() -> String {
    let kinds = event_kinds()
        .into_iter()
        .map(|k| format!("  {:?},", k))
        .collect::<Vec<_>>()
        .join("\n");
    let tools = SUBAGENT_TOOLS
        .iter()
        .map(|t| format!("  {t:?},"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Gerado por `pnpm codegen` a partir do `crates/app/src/protocol.rs`.\n\
         // Não editar à mão: os nomes aqui são os que o Rust serializa, e é isso\n\
         // que os torna verdadeiros dos dois lados do cano.\n\
         \n\
         /** Os `kind` que um evento pode ter, tal como o adaptador os lê. */\n\
         export const EVENT_KINDS = Object.freeze([\n{kinds}\n]);\n\
         \n\
         /** A ferramenta que abre um subagente, em todas as grafias que a CLI\n\
          *  já lhe deu. Era `Task`, é `Agent`; o guarda que comparava com a\n\
          *  primeira nunca disparou. */\n\
         export const SUBAGENT_TOOLS = Object.freeze([\n{tools}\n]);\n\
         \n\
         /** É esta a chamada que abre um subagente? */\n\
         export function isSubagentTool(name) {{\n\
         \x20 return SUBAGENT_TOOLS.includes(name);\n\
         }}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// O `one_of_each` é escrito à mão, portanto tem de haver quem o obrigue a
    /// estar completo — senão um `RunEvent` novo entra no cano sem nunca ser
    /// nomeado do outro lado, que é a falha que este módulo existe para
    /// impedir.
    ///
    /// Conta-se pelo que o `serde` escreve: um `kind` vazio ou repetido quer
    /// dizer variante esquecida ou duplicada.
    #[test]
    fn every_listed_event_has_a_kind_and_no_two_share_one() {
        let all = one_of_each();
        let kinds: Vec<String> = all.iter().map(kind_of).collect();
        for (event, kind) in all.iter().zip(&kinds) {
            assert!(!kind.is_empty(), "{event:?} serializa sem `kind`");
        }
        let mut unicos = kinds.clone();
        unicos.sort();
        unicos.dedup();
        assert_eq!(unicos.len(), kinds.len(), "duas variantes com o mesmo kind");
    }

    /// A lista acima é escrita à mão, e uma lista escrita à mão que ninguém
    /// obriga a estar completa é a forma exacta do defeito que este módulo
    /// existe para fechar. Lê-se o enum na fonte e exige-se cobertura: uma
    /// variante nova parte aqui, no CI, e não no cano em silêncio.
    #[test]
    fn every_variant_is_listed() {
        let fonte = include_str!("../../ports/src/lib.rs");
        let corpo = fonte
            .split_once("pub enum RunEvent {")
            .expect("o `RunEvent` mudou de forma; actualizar este teste")
            .1;
        let corpo = corpo.split_once("\n}").expect("enum sem fim").0;

        let declaradas: Vec<&str> = corpo
            .lines()
            .filter_map(|l| {
                let t = l.trim_end();
                // Uma variante está a quatro espaços e abre um bloco; tudo o
                // resto é campo, comentário ou atributo.
                let nome = t.strip_prefix("    ")?.strip_suffix(" {")?;
                nome.chars()
                    .next()
                    .filter(char::is_ascii_uppercase)
                    .map(|_| nome)
            })
            .collect();
        assert!(
            declaradas.len() > 10,
            "extraí {} variantes, o que quer dizer que o parser deixou de servir",
            declaradas.len(),
        );

        let listadas: std::collections::HashSet<String> = one_of_each()
            .iter()
            .map(|e| format!("{e:?}").split_whitespace().next().unwrap().to_string())
            .collect();
        let em_falta: Vec<&&str> = declaradas
            .iter()
            .filter(|v| !listadas.contains(**v))
            .collect();
        assert!(
            em_falta.is_empty(),
            "variantes do RunEvent que o sidecar nunca virá a conhecer: {em_falta:?}",
        );
    }

    #[test]
    fn the_generated_module_carries_both_halves() {
        let js = javascript();
        // O que partiu: a grafia que o modelo usa.
        assert!(js.contains("\"Agent\""), "{js}");
        assert!(js.contains("\"Task\""), "a grafia antiga continua a valer");
        // E uma amostra de kinds que têm de lá estar.
        for kind in ["usage", "tool_use", "approval_answered", "done"] {
            assert!(js.contains(&format!("{kind:?}")), "falta o kind {kind}");
        }
    }
}
