[package]
name = "harness-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ts-rs = { version = '10', features = ['serde-compat'] }
harness-domain = { path = "../domain" }
harness-ports = { path = "../ports" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "process", "io-util"] }
tokio-util = { version = "0.7", features = ["rt"] }
uuid = { version = "1", features = ["v4"] }
